// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';

export function AnalyzeExcerpt(arg1:string):Promise<backend.DashboardData>;

export function AnalyzeFile(arg1:string):Promise<backend.DashboardData>;

export function ExtractTimelineMarkers(arg1:string):Promise<Array<string>>;

export function GetDashboard():Promise<backend.DashboardData>;

export function GetServiceDiagnostics():Promise<backend.SystemDiagnostics>;

export function InstallMissingDependencies():Promise<backend.SystemDiagnostics>;

export function PickAndAnalyzeFile():Promise<backend.DashboardData>;
