// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AnalyzeExcerpt(arg1) {
  return window['go']['main']['App']['AnalyzeExcerpt'](arg1);
}

export function AnalyzeFile(arg1) {
  return window['go']['main']['App']['AnalyzeFile'](arg1);
}

export function ExportLogPackageDialog() {
  return window['go']['main']['App']['ExportLogPackageDialog']();
}

export function ExtractTimelineMarkers(arg1) {
  return window['go']['main']['App']['ExtractTimelineMarkers'](arg1);
}

export function GetDashboard() {
  return window['go']['main']['App']['GetDashboard']();
}

export function GetServiceDiagnostics() {
  return window['go']['main']['App']['GetServiceDiagnostics']();
}

export function InstallMissingDependencies() {
  return window['go']['main']['App']['InstallMissingDependencies']();
}

export function PickAndAnalyzeFile() {
  return window['go']['main']['App']['PickAndAnalyzeFile']();
}

export function Quit() {
  return window['go']['main']['App']['Quit']();
}

export function ReportClientError(arg1, arg2, arg3) {
  return window['go']['main']['App']['ReportClientError'](arg1, arg2, arg3);
}
